spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: never
    job:
      name: "exampleJob3"
      enabled: false
server:
  port: 8081
